$primary = rgb(e8e8e8)
$surface = rgb(000000)
$secondary = rgb(cccccc)
$error = rgb(d4d4d4)
$tertiary = rgb(999999)
$surface_lowest = rgb(030303)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
