#! /bin/sh
zsh ~/.config/bspwm/scripts/startUp.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

# MONITOR WORKSPACES
bspc monitor DP-2 -d 1 2 3 
bspc monitor DP-0 -d 4 5 6
bspc monitor HDMI-0 -d 7 8 9
xrandr --output DP-2 --primary 
# CONFIGURATION
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# RULES
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a vesktop desktop=^7
bspc rule -a steam_app_* desktop=^3 follow=on state=fullscreen
bspc rule -a osu!.exe desktop=^6 follow=on state=fullscreen # por alguna razon, el desktop que pilla osu es posicional de izquierda a derecha
