#! /bin/sh

# MONITOR WORKSPACES
bspc monitor DP-2 -d 1 2 3 
bspc monitor DP-0 -d 4 5 6
bspc monitor HDMI-0 -d 7 8 9
# CONFIGURATION
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config active_border_color '#292e42'
bspc config normal_border_color '#292e42'
bspc config focused_border_color '#7aa2f7'


# RULES
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a spotify desktop=8
bspc rule -a vesktop desktop=7
bspc rule -a discord desktop=7
bspc rule -a steam_app_* desktop=3 follow=on state=fullscreen
bspc rule -a osu!.exe desktop=3 follow=on state=fullscreen
bspc rule -a steam desktop=3

zsh ~/.config/bspwm/scripts/startUp.sh &
# es una guarrada pero con esto pongo el monitor DP-2 como primario
lxappearance &
sleep 1
killall lxappearance
xrandr --output DP-2 --primary
xrandr --output DP-2 --mode 2560x1440 --rate 165
xrandr --output DP-0 --mode 1920x1080 --rate 144
sxhkd &
