source = /home/yasai/.config/hypr/config/environment.conf
source = /home/yasai/.config/hypr/config/displays.conf
source = /home/yasai/.config/hypr/config/config.conf
source = /home/yasai/.config/hypr/config/devices.conf
source = /home/yasai/.config/hypr/config/theme.conf
source = /home/yasai/.config/hypr/config/windowrules.conf
source = /home/yasai/.config/hypr/config/keybinds.conf
source = /home/yasai/.config/hypr/config/nvidia.conf
source = /home/yasai/.config/hypr/config/autostart.conf

