preload = /home/yasai/Images/Wallpapers/sushi-dark.png


wallpaper = DP-2, /home/yasai/Images/Wallpapers/sushi-dark.png
wallpaper = DP-0, /home/yasai/Images/Wallpapers/sushi-dark.png
wallpaper = HDMI-A-1, /home/yasai/Images/Wallpapers/sushi-dark.png
ipc = off
