#!/bin/sh

# Directories to search
directories="
$HOME/Documents/projects
$HOME/Documents
$HOME/dotfiles
$HOME/dotfiles/config
$HOME
"

# If an argument is provided, use it as the directory
if [ $# -eq 1 ]; then
    dir=$1
else
    # Find directories and use fzf to select one
    dir=`find $directories -mindepth 1 -maxdepth 1 -type d | fzf`
fi

# If no directory is selected, exit
if [ -z "$dir" ]; then
    exit 0
fi

# Session name based on directory name
session=`basename "$dir" | tr . _`
tmux_running=`pgrep tmux`
inside_tmux=`if [ "$TERM_PROGRAM" = 'tmux' ]; then echo 'true'; else echo 'false'; fi`

# Check if tmux session exists
if tmux has-session -t="$session" 2>/dev/null; then
    # If inside tmux, switch client
    if [ "$inside_tmux" = 'true' ]; then
        tmux switch-client -t "$session"
        exit 0
    fi
    # If not inside tmux, attach session
    tmux attach-session -t "$session"
    exit 0
fi

# Create new tmux session
tmux new-session -d -s "$session" -c "$dir"

# Switch or attach to session based on environment
if [ "$inside_tmux" = 'true' ]; then
    tmux switch-client -t "$session"
else
    tmux attach-session -t "$session"
fi
