exec-once = waybar 
exec-once = hyprpaper
exec-once = udiskie
exec-once = dex --autostart
exec-once = clipboard-sync
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = waypaper --restore
exec-once = xhost +SI:localuser:root 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = fcitx5
exec-once = xrandr --output DP-2 --primary
