hl.on("hyprland.start", function ()
  hl.exec_cmd("udiskie")
  hl.exec_cmd("dex --autostart")
  hl.exec_cmd("clipboard-sync")
  hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("xrandr --output DP-2 --primary")
  hl.exec_cmd("qs -c noctalia-shell")
end)
