# exec-once = waybar 
# exec-once = hyprpaper
exec-once = udiskie
exec-once = dex --autostart
exec-once = clipboard-sync
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = fcitx5
exec-once = xrandr --output DP-2 --primary
exec-once = qs -c noctalia-shell
