# Vesktop always on workspace 8
windowrule = match:class ^(discord | vesktop)$, workspace 8 
windowrule = match:class (discord | vesktop), no_initial_focus on

# game rules
windowrule = match:class ^(steam)$, workspace 5
windowrule = match:class (steam), no_initial_focus on
windowrule = match:class ^(steam_app_)(.*)$, fullscreen_state 3
windowrule = match:class ^(minecraft-launcher)(.*)$, workspace 5

# Visual studio code rules
windowrule = match:class ^(code-url-handler)$, opacity 0.9
windowrule = match:class ^(xdg-desktop-portal-gtk)$ # open files and folders rules, float, 
windowrule = match:class ^(Xdg-desktop-portal-gtk)$, no_blur on

# Disable blur from pop ups (X11)
# windowrule = match:class ^()$, noblur, title:^()$

windowrule = match:class .* # You'll probably like this., suppressevent maximize, 
